---
- include:              '../tasks/install_packages.yml'
- include:              '../tasks/template_files.yml'
- include:              '../tasks/lines_in_files.yml'
- include:              '../tasks/install_files.yml'
- include:              '../tasks/enable_services.yml'
- include:              '../tasks/start_services.yml'
- include:              '../tasks/restart_services.yml'
  when:                 template_files_result.changed or
                        lines_in_files_result.changed
